// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_fcOnH-kVDvWEDR4aaxZqbRw_wctx598',
    appId: '1:688523796044:web:84ffdedd9c960eb14ddee9',
    messagingSenderId: '688523796044',
    projectId: 'fir-practice-n',
    authDomain: 'fir-practice-n.firebaseapp.com',
    storageBucket: 'fir-practice-n.appspot.com',
    measurementId: 'G-P904BQVP2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwV_sFPDdVew0iNf5NDq0XpZGsPsBryWI',
    appId: '1:688523796044:android:90bc5c91736fd4494ddee9',
    messagingSenderId: '688523796044',
    projectId: 'fir-practice-n',
    storageBucket: 'fir-practice-n.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhGC17jSqzQsLf0EFT97idc7V_3Dh6kr4',
    appId: '1:688523796044:ios:dd48dad9419a162b4ddee9',
    messagingSenderId: '688523796044',
    projectId: 'fir-practice-n',
    storageBucket: 'fir-practice-n.appspot.com',
    iosBundleId: 'com.example.firebasePrcatice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhGC17jSqzQsLf0EFT97idc7V_3Dh6kr4',
    appId: '1:688523796044:ios:09ea84895be409fb4ddee9',
    messagingSenderId: '688523796044',
    projectId: 'fir-practice-n',
    storageBucket: 'fir-practice-n.appspot.com',
    iosBundleId: 'com.example.firebasePrcatice.RunnerTests',
  );
}
